# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 17ee3d82e031e53d6390ce49858cfbe6e5df1a50feaf2084f36eb2a80fd22d4043d8d06852d0782b7eeb51c855e670109fa77824d5f97c474e1f19ef7ec34db1

test:
  secret_key_base: 9383a58e94ccb6eb0f7719d8d3d3816e3af4133e82701e9b0fa76730f947f22337d3d3e023e3183ca3f074bdaad1804fd1cb83d2c6d5db2df57ba69cd5e23159

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
